Fix LDAP Identity with non-zero user_enabled_default
The LDAP Identity backend was not properly using the
user_enabled_default option as a string. This caused
operations to fail with

 TypeError: unsupported operand type(s) for &: 'str' and 'int'

Partial-Bug: #1210175

Change-Id: I54931e669186871d18dea088870945b9de40d573